name: CI/CD Pipeline
on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11
          
      - name: Install dependencies
        run: pip install pandas scikit-learn joblib
        
      - name: Train model
        run: python train_model.py
        
      - name: List files
        run: ls -la
        
      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            linear_model.txt
            linear_model.pkl
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
